// api/reportingAPI.js
// Author: Gemini
// Purpose: API functions for generating and managing system-wide reports for administrators.

/**
 * Retrieves all previously generated reports.
 * @param {Object} db - Database connection
 * @param {Function} callback - Callback function(err, results)
 */
function getReports(db, callback) {
  const query = `
    SELECT
      r.Report_ID,
      r.Admin_ID,
      u.Name AS Generated_By,
      r.Period_Type,
      r.Period_Start,
      r.Period_End,
      r.Generated_At,
      r.Summary_Data
    FROM Report r
    JOIN User u ON r.Admin_ID = u.User_ID
    ORDER BY r.Generated_At DESC
  `;

  db.query(query, (err, results) => {
    if (err) {
      console.error('Error fetching reports:', err);
      return callback(err, null);
    }
    callback(null, results);
  });
}

/**
 * Generates a new system report for a given period and saves it to the database.
 * @param {Object} db - Database connection
 * @param {number} adminId - The ID of the admin generating the report.
 * @param {string} periodType - 'Monthly' or 'Yearly'.
 * @param {string} periodStart - The start date of the report period (e.g., '2025-10-01').
 * @param {string} periodEnd - The end date of the report period (e.g., '2025-10-31').
 * @param {Function} callback - Callback function(err, result)
 */
function generateReport(db, adminId, periodType, periodStart, periodEnd, callback) {
  // This is a complex operation that would involve multiple queries.
  // For this implementation, we will perform a few sample aggregations.
  
  const summaryData = {};
  let queriesCompleted = 0;
  const totalQueries = 3; // The number of async queries we will run.

  // 1. Get count of new patients in the period
  const newPatientsQuery = `
    SELECT COUNT(User_ID) AS new_patients_count
    FROM User
    WHERE Role = 'Patient' AND Created_At BETWEEN ? AND ?
  `;
  db.query(newPatientsQuery, [periodStart, periodEnd], (err, results) => {
    if (err) return callback(err);
    summaryData.new_patients_count = results[0].new_patients_count;
    checkCompletion();
  });

  // 2. Get count of total blood sugar readings logged in the period
  const totalReadingsQuery = `
    SELECT COUNT(Reading_ID) AS total_readings_count
    FROM Sugar_Reading
    WHERE DateTime BETWEEN ? AND ?
  `;
  db.query(totalReadingsQuery, [periodStart, periodEnd], (err, results) => {
    if (err) return callback(err);
    summaryData.total_readings_count = results[0].total_readings_count;
    checkCompletion();
  });

  // 3. Get count of alerts generated in the period
  const totalAlertsQuery = `
    SELECT COUNT(Alert_ID) AS total_alerts_count
    FROM Alert
    WHERE Sent_At BETWEEN ? AND ?
  `;
  db.query(totalAlertsQuery, [periodStart, periodEnd], (err, results) => {
    if (err) return callback(err);
    summaryData.total_alerts_count = results[0].total_alerts_count;
    checkCompletion();
  });
  
  // This function checks if all queries are done before saving the report.
  function checkCompletion() {
    queriesCompleted++;
    if (queriesCompleted === totalQueries) {
      saveReport();
    }
  }
  
  // This function saves the final aggregated data to the 'report' table.
  function saveReport() {
    const summaryDataJSON = JSON.stringify(summaryData);

    const insertQuery = `
      INSERT INTO Report (Admin_ID, Period_Type, Period_Start, Period_End, Generated_At, Summary_Data)
      VALUES (?, ?, ?, ?, NOW(), ?)
    `;
    
    db.query(insertQuery, [adminId, periodType, periodStart, periodEnd, summaryDataJSON], (err, results) => {
      if (err) {
        console.error('Error saving report:', err);
        return callback(err);
      }
      
      const newReport = {
        report_id: results.insertId,
        admin_id: adminId,
        period_type: periodType,
        summary_data: summaryData
      };
      console.log(`New report (ID: ${results.insertId}) generated by Admin ${adminId}.`);
      callback(null, newReport);
    });
  }
}

module.exports = {
  getReports,
  generateReport
};
